### ISSUE TITLE
Text not changing when user submits language form

### ISSUE THREAD

**Issue by brylie** [SustainableUrbanDesign/app#26]
We added a language selection form recently. However, it doesn't seem to change the user's language when the form is submitted.

## Task
Fix the user language form so that the UI texts change when the form is submitted.

**Comment by MaxThakurCodes** [comment]
Text is not changing still.

**Comment by brylie** [comment]
Hey Max. Apologies for not holding the weekly review meeting this weekend.

Would you please post an update here as to your progress with this issue? Should we leave it assigned to you or place it in the backlog?

**Comment by brylie** [comment]
I'm just following up on this task. Is the bug still present?
