### ISSUE TITLE
How To Make an Issue

### ISSUE THREAD

**Issue by MaxThakurCodes** [SustainableUrbanDesign/app#35]
# How To Make an Issue

## First

Check if an issue is already made for a problem like your's or your's by other people.

## Second

Make the issue if no other issue fixes your problem.

### Title

For the issue make sure you make a **descriptive title**. Describing the issue you are having

### Description

For the description, please describe what is happening. Provide the error message inside of two grave accents ``. Then, describe what you were doing when you got the error.

## Third

Double check your issue in preview, make sure it looks how you wanted it to.

## Finally

Click "Submit New Issue", then the issue will be reviewed by a developer, or manager then it will be labeled and will be handled with by the right people.

## Note

Issues might not get labeled right away please leave atleast 24-48 hours for the developers to get to the issue.

**Comment by brylie** [comment]
Instead of this living in an issue description, let's include it in a CONTRIBUTING.md

http://mozillascience.github.io/working-open-workshop/contributing/

**Comment by MaxThakurCodes** [comment]
Replaced with [CONTRIBUTING.md](CONTRIBUTING.md)
