### ISSUE TITLE
Create initial app logo and mobile icons

### ISSUE THREAD

**Issue by brylie** [SustainableUrbanDesign/app#47]
Our project needs a logo. This task is good for anyone who is interested in graphic design.

## Task
- create a few logo ideas for review and discussion
- open the discussion to get feedback and suggestions for refinement (in this issue)
- once we have agreed on a "final" logo design, create some mobile app icons based on the design
    - iOS icon(s)
    - Android icon
    - favicon
    - a large version of the icon for other print materials
- provide the logo in open formats, namely SVG and PNG

**Comment by rmk118** [comment]
![Sustainable_Urban_Design](https://user-images.githubusercontent.com/67233373/88123515-a3ad6380-cb90-11ea-8703-a8d9dd6db5f8.png)

Just a thought? I'm not the most skilled programmer (yet), but I'm trying to find ways to help.

**Comment by brylie** [comment]
@rmk118 thanks for contributing the logo. Can you please do the following?

- [ ] provide the logo in a format like SVG so it can be modified
- [ ] provide links to the sources where you got the home icon, leafy branch, and the typeface used for the words

**Comment by rmk118** [comment]
Sure, I made that one in Canva just to see if you guys would like the concept. I'll make a more final version in Adobe Illustrator; it will have to look slightly different but it will be safer with regards to licensing/copyright/etc. I can definitely provide it in SVG format with attribution links when I'm done. Please let me know if there's any changes you'd like me to make (ex. font, color scheme)

**Comment by rmk118** [comment]
[logo.zip](https://github.com/SustainableUrbanDesign/app/files/4967692/logo.zip)
I've attached the updated logo in PNG, JPG, and SVG format inside the zip file. The house icon was modified from https://www.smashingmagazine.com/2015/07/freebie-smashicons-icon-set/ (the website says it can be modified and/or used in commercial projects and no attribution is required). The leafy branch is from Adobe Stock (https://stock.adobe.com/images/vector-illustration-set-of-branches-leaves-twigs-garden-grasses-in-line-style-for-floral-patterns-bouquets-and-compositions-in-white-background-elements-for-greeting-cards/202061929) and was obtained under their Standard License. The text is in Optima Bold (a free font).

**Comment by brylie** [comment]
OK, we probably need an openly licensed leafy branch. One where we can release the derivative work under an open license, such as Creative Commons.

**Comment by rmk118** [comment]
Okay, here is a ZIP file with an updated logo. Both the house and branch are from this website (https://svgsilh.com/ffc107/), where everything is licensed under the Creative Commons CC0. Font is Josefin Sans (a free font).
[logo2.zip](https://github.com/SustainableUrbanDesign/app/files/4973222/logo2.zip)

**Comment by brylie** [comment]
@rmk118 I have uploaded this to be the organization icon on GitHub. Thanks for the design work :-)

**Comment by brylie** [comment]
@all-contributors please add @rmk118 for design
